import type { Category } from './categories';
import type { FeatureWithVotes, FeatureStatus } from './features';

const IMG = 'https://iylihysvbwlyrmcedsaj.supabase.co/storage/v1/object/public/category-images';

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'cat-1', name: 'Productivity',
    description: 'Tools and features to boost your daily workflow',
    image: `${IMG}/productivity.jpg`, created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cat-2', name: 'AI & Machine Learning',
    description: 'Smart features powered by artificial intelligence',
    image: `${IMG}/ai-machine-learning.jpg`, created_at: '2026-01-02T00:00:00Z',
  },
  {
    id: 'cat-3', name: 'Design Tools',
    description: 'Creative tools for designers and visual thinkers',
    image: `${IMG}/design-tools.jpg`, created_at: '2026-01-03T00:00:00Z',
  },
  {
    id: 'cat-4', name: 'Developer Experience',
    description: 'Improve the developer workflow and tooling',
    image: `${IMG}/developer-experience.jpg`, created_at: '2026-01-04T00:00:00Z',
  },
  {
    id: 'cat-5', name: 'Mobile Apps',
    description: 'Features for native and cross-platform mobile development',
    image: `${IMG}/mobile-apps.jpg`, created_at: '2026-01-05T00:00:00Z',
  },
  {
    id: 'cat-6', name: 'Cloud Infrastructure',
    description: 'Scalable cloud services and deployment tools',
    image: `${IMG}/cloud-infrastructure.jpg`, created_at: '2026-01-06T00:00:00Z',
  },
  {
    id: 'cat-7', name: 'Security & Privacy',
    description: 'Keep your data and users safe',
    image: `${IMG}/security-privacy.jpg`, created_at: '2026-01-07T00:00:00Z',
  },
  {
    id: 'cat-8', name: 'Data Analytics',
    description: 'Insights, dashboards, and data visualization',
    image: `${IMG}/data-analytics.jpg`, created_at: '2026-01-08T00:00:00Z',
  },
  {
    id: 'cat-9', name: 'Social Features',
    description: 'Community, sharing, and collaboration tools',
    image: `${IMG}/social-features.jpg`, created_at: '2026-01-09T00:00:00Z',
  },
  {
    id: 'cat-10', name: 'Accessibility',
    description: 'Make your product usable by everyone',
    image: `${IMG}/accessibility.jpg`, created_at: '2026-01-10T00:00:00Z',
  },
];

function f(
  id: string, catId: string, title: string, desc: string,
  up: number, down: number,
  status: FeatureStatus = 'requested',
): FeatureWithVotes {
  return {
    id, title, description: desc, status, voter_id: 'system', category_id: catId,
    created_at: '2026-01-15T00:00:00Z',
    upvotes_count: up, downvotes_count: down, score: up - down, my_vote: 0,
  };
}

export const MOCK_FEATURES: Record<string, FeatureWithVotes[]> = {
  'cat-1': [
    f('f1-1','cat-1','Keyboard shortcuts for common actions','Add customizable keyboard shortcuts to speed up repetitive tasks.',24,3),
    f('f1-2','cat-1','Focus mode with notification blocking','A distraction-free mode that silences non-critical notifications.',32,1,'in_progress'),
    f('f1-3','cat-1','Daily summary email digest','Automated email summarizing activity and pending tasks each morning.',15,7),
    f('f1-4','cat-1','Quick-add widget for tasks','A floating widget to capture tasks without switching context.',20,2),
    f('f1-5','cat-1','Pomodoro timer integration','Built-in work/break timer following the Pomodoro technique.',18,5),
    f('f1-6','cat-1','Smart task prioritization','Automatically re-order tasks based on due date and importance.',27,4),
    f('f1-7','cat-1','Calendar sync','Two-way sync with Google Calendar and Outlook.',35,3,'shipped'),
    f('f1-8','cat-1','Template library for recurring workflows','Pre-built templates for common project types and workflows.',12,1),
    f('f1-9','cat-1','Batch actions on multiple items','Select and move, tag, or archive many items at once.',22,6),
    f('f1-10','cat-1','Global search across all workspaces','Search notes, tasks, and files from one unified search bar.',40,2),
  ],
  'cat-2': [
    f('f2-1','cat-2','Smart auto-categorization','Use ML to automatically categorize incoming items based on content.',41,5),
    f('f2-2','cat-2','Natural language search','Search using plain English queries instead of exact keywords.',28,2),
    f('f2-3','cat-2','AI-powered writing assistant','Suggest edits, grammar fixes, and tone improvements inline.',36,8),
    f('f2-4','cat-2','Predictive text completion','Context-aware text predictions as you type.',19,3),
    f('f2-5','cat-2','Automated meeting notes','Transcribe and summarize meetings in real time.',44,4,'in_progress'),
    f('f2-6','cat-2','Sentiment analysis on feedback','Tag user feedback as positive, negative, or neutral automatically.',14,6),
    f('f2-7','cat-2','Smart duplicate detection','Flag potential duplicate entries before they are created.',23,2),
    f('f2-8','cat-2','Image recognition for uploads','Auto-tag and describe uploaded images using vision models.',17,5),
    f('f2-9','cat-2','Anomaly detection in metrics','Alert when key metrics deviate from expected patterns.',31,3),
    f('f2-10','cat-2','AI chatbot for user support','An in-app chatbot that answers common questions instantly.',38,9),
  ],
  'cat-3': [
    f('f3-1','cat-3','Built-in color palette generator','Generate harmonious palettes from a base color with CSS export.',19,4),
    f('f3-2','cat-3','Drag-and-drop layout builder','Visual layout builder with snap-to-grid and responsive preview.',35,8),
    f('f3-3','cat-3','Asset library with tagging','Organize design assets with custom tags for easy reuse.',12,1),
    f('f3-4','cat-3','Real-time design collaboration','Multiple users editing the same canvas simultaneously.',42,3,'shipped'),
    f('f3-5','cat-3','Component version history','Track changes to design components with rollback support.',26,5),
    f('f3-6','cat-3','Auto-generate style guides','Export a living style guide from your design tokens.',18,2),
    f('f3-7','cat-3','Icon search and insertion','Searchable icon library with one-click insertion into designs.',30,4),
    f('f3-8','cat-3','Responsive breakpoint preview','Preview designs at mobile, tablet, and desktop sizes instantly.',24,1),
    f('f3-9','cat-3','Figma import/export','Seamless round-trip sync between the app and Figma files.',37,6),
    f('f3-10','cat-3','Contrast checker for accessibility','Inline WCAG contrast ratio checker for text and backgrounds.',21,0),
  ],
  'cat-4': [
    f('f4-1','cat-4','Hot reload for config changes','Apply configuration changes without restarting the dev server.',45,2),
    f('f4-2','cat-4','Inline API documentation','Hover tooltips showing API docs and type hints in the editor.',22,3),
    f('f4-3','cat-4','One-click environment setup','Spin up a fully configured dev environment from a single command.',39,4),
    f('f4-4','cat-4','Built-in database seeder','Populate the database with realistic test data in one step.',16,1),
    f('f4-5','cat-4','Visual dependency graph','Interactive graph showing package and module dependencies.',20,5),
    f('f4-6','cat-4','Auto-fix lint errors on save','Automatically apply linter suggestions when a file is saved.',33,7),
    f('f4-7','cat-4','PR preview deployments','Deploy every pull request to a unique preview URL.',48,2,'in_progress'),
    f('f4-8','cat-4','Error boundary dashboard','Aggregated view of all runtime errors with stack traces.',25,3),
    f('f4-9','cat-4','CLI plugin system','Extend the CLI with community-built plugins and scripts.',14,2),
    f('f4-10','cat-4','Performance profiling tab','Built-in flame graph and memory profiler for debugging.',29,4),
  ],
  'cat-5': [
    f('f5-1','cat-5','Offline mode with sync','Use the app offline and sync changes when reconnected.',38,3),
    f('f5-2','cat-5','Push notification scheduling','Schedule push notifications with timezone-aware delivery.',21,4),
    f('f5-3','cat-5','Biometric authentication','Login with fingerprint or Face ID on supported devices.',34,2,'shipped'),
    f('f5-4','cat-5','Deep linking support','Open specific screens directly from URLs or notifications.',27,1),
    f('f5-5','cat-5','App widget for home screen','Glanceable home screen widget showing key information.',19,5),
    f('f5-6','cat-5','Dark mode auto-switch','Follow the device system theme automatically.',42,3),
    f('f5-7','cat-5','Gesture-based navigation','Swipe gestures for common actions like delete and archive.',16,6),
    f('f5-8','cat-5','In-app update prompts','Prompt users to update when a new version is available.',23,8),
    f('f5-9','cat-5','Haptic feedback on interactions','Subtle vibration feedback on button presses and swipes.',11,3),
    f('f5-10','cat-5','Adaptive layout for tablets','Optimized multi-pane layout on larger screens.',30,2),
  ],
  'cat-6': [
    f('f6-1','cat-6','One-click deploy to production','Ship to production with a single button press and rollback.',50,4,'in_progress'),
    f('f6-2','cat-6','Auto-scaling based on traffic','Dynamically adjust resources based on real-time load.',37,2),
    f('f6-3','cat-6','Multi-region deployment','Deploy to multiple geographic regions for lower latency.',28,5),
    f('f6-4','cat-6','Infrastructure as code templates','Pre-built Terraform/Pulumi templates for common stacks.',22,3),
    f('f6-5','cat-6','Cost monitoring dashboard','Real-time spending breakdown by service and environment.',33,1),
    f('f6-6','cat-6','Blue-green deployments','Zero-downtime deployments with traffic shifting.',26,2),
    f('f6-7','cat-6','Managed database backups','Automatic daily backups with point-in-time restore.',41,1),
    f('f6-8','cat-6','Edge function support','Run serverless functions at the edge for faster responses.',18,4),
    f('f6-9','cat-6','Container registry integration','Built-in Docker registry with vulnerability scanning.',15,3),
    f('f6-10','cat-6','Uptime monitoring with alerts','Monitor service health and alert on downtime via Slack or email.',35,2),
  ],
  'cat-7': [
    f('f7-1','cat-7','Two-factor authentication','Add TOTP-based 2FA for all user accounts.',46,1,'shipped'),
    f('f7-2','cat-7','Audit log for all actions','Immutable log of who did what and when.',32,3),
    f('f7-3','cat-7','Role-based access control','Fine-grained permissions based on user roles.',39,2),
    f('f7-4','cat-7','Data encryption at rest','Encrypt all stored data with AES-256.',28,1),
    f('f7-5','cat-7','Session timeout controls','Configurable inactivity timeouts per security level.',17,4),
    f('f7-6','cat-7','IP allowlist for admin panels','Restrict admin access to trusted IP addresses only.',21,5),
    f('f7-7','cat-7','GDPR data export','Let users download all their personal data in one click.',35,2),
    f('f7-8','cat-7','Vulnerability scanning in CI','Automated security scans on every pull request.',24,3),
    f('f7-9','cat-7','Password strength meter','Real-time feedback on password strength during signup.',13,1),
    f('f7-10','cat-7','SSO with SAML and OAuth','Enterprise single sign-on for teams and organizations.',40,4),
  ],
  'cat-8': [
    f('f8-1','cat-8','Custom dashboard builder','Drag-and-drop widgets to build personalized dashboards.',36,5,'in_progress'),
    f('f8-2','cat-8','Export reports to PDF','Generate polished PDF reports from any data view.',22,2),
    f('f8-3','cat-8','Real-time streaming charts','Live-updating charts for monitoring real-time data.',29,3),
    f('f8-4','cat-8','Cohort analysis tool','Analyze user behavior grouped by signup date or segment.',18,4),
    f('f8-5','cat-8','Funnel visualization','Visualize drop-off at each step of a user journey.',25,1),
    f('f8-6','cat-8','SQL query editor','Write and save custom SQL queries against your data.',31,6),
    f('f8-7','cat-8','Scheduled report emails','Automatically email reports on a daily or weekly schedule.',20,2),
    f('f8-8','cat-8','Data source connectors','Connect to Postgres, BigQuery, Snowflake, and more.',38,3),
    f('f8-9','cat-8','Anomaly highlighting in charts','Automatically flag unusual data points in visualizations.',15,1),
    f('f8-10','cat-8','Shareable dashboard links','Generate public or password-protected dashboard URLs.',27,4),
  ],
  'cat-9': [
    f('f9-1','cat-9','Comment threads on any item','Add threaded discussions to tasks, docs, and files.',33,4),
    f('f9-2','cat-9','@mention notifications','Notify users when they are mentioned in a comment.',28,2),
    f('f9-3','cat-9','Activity feed','A chronological feed of recent actions by your team.',21,3),
    f('f9-4','cat-9','Reactions and emoji responses','React to comments and updates with emoji.',16,5),
    f('f9-5','cat-9','Shared workspaces for teams','Collaborate in shared spaces with granular permissions.',37,2,'shipped'),
    f('f9-6','cat-9','User profiles with bios','Public profiles showing contributions, role, and bio.',12,4),
    f('f9-7','cat-9','Follow items for updates','Subscribe to specific items to get notified of changes.',24,1),
    f('f9-8','cat-9','Invite links for onboarding','Generate shareable links to invite new team members.',19,2),
    f('f9-9','cat-9','Leaderboard for top contributors','Gamified ranking of most active community members.',14,7),
    f('f9-10','cat-9','Direct messaging between users','Private 1-on-1 messaging within the platform.',30,6),
  ],
  'cat-10': [
    f('f10-1','cat-10','Screen reader optimization','Ensure all UI elements have proper ARIA labels and roles.',34,1),
    f('f10-2','cat-10','Keyboard-only navigation','Full app navigation without requiring a mouse.',29,2,'in_progress'),
    f('f10-3','cat-10','High contrast theme','An alternative theme with stronger contrast ratios.',22,3),
    f('f10-4','cat-10','Font size scaling','User-controlled text sizing from small to extra-large.',26,1),
    f('f10-5','cat-10','Reduced motion mode','Disable animations for users sensitive to motion.',18,0),
    f('f10-6','cat-10','Alt text for all images','Enforce descriptive alt text on every uploaded image.',20,2),
    f('f10-7','cat-10','Color-blind friendly palettes','Avoid red/green combos; use patterns and labels for clarity.',31,3),
    f('f10-8','cat-10','Focus indicator styling','Clear visible focus rings on all interactive elements.',16,1),
    f('f10-9','cat-10','Captioned video content','Auto-generate captions for all video and audio content.',24,4),
    f('f10-10','cat-10','Accessibility audit reports','Automated WCAG compliance reports for every page.',28,2),
  ],
};
